@base_url = localhost:8888
@first_name = Reza
@last_name = Fauzan Adhima
@email = reza.fauzan.adhima.04@gmail.com
@address = Jakarta, Indonesia
@phone = +6285183356072
@password = test1111
@confirm_password = test1111

POST /users HTTP/1.1
Host: {{base_url}}
Content-Type: application/json

{
    "first_name": "{{first_name}}",
    "last_name": "{{last_name}}",
    "email": "{{email}}",
    "address": "{{address}}",
    "phone": "{{phone}}",
    "password": "{{password}}",
    "confirm_password": "{{confirm_password}}"
}

### Test case: Create user with missing first name length less then 4
POST /users HTTP/1.1
Host: {{base_url}}
Content-Type: application/json

{
    "first_name": "Eza",
    "last_name": "{{last_name}}",
    "email": "{{email}}",
    "address": "{{address}}",
    "phone": "{{phone}}",
    "password": "{{password}}",
    "confirm_password": "{{confirm_password}}"
}

###
GET /users HTTP/1.1
Host: {{base_url}}

### Update User
PATCH /users/1 HTTP/1.1
Host: {{base_url}}
Content-Type: application/json

{
    "first_name": "Reza Update",
    "last_name": "Fauzan Update",
    "email": "reza.update@gmail.com",
    "address": "Bandung, Indonesia",
    "phone": "+6281234567890"
}

### Test Case: Update Invalid Email
PATCH /users/1 HTTP/1.1
Host: {{base_url}}
Content-Type: application/json

{
    "first_name": "Reza Update",
    "last_name": "Fauzan Update",
    "email": "invalid-email",
    "address": "Bandung, Indonesia",
    "phone": "+6281234567890"
}

### Delete User
DELETE /users/1 HTTP/1.1
Host: {{base_url}}

### Test Case: Delete User With Invalid ID
DELETE /users/999999 HTTP/1.1
Host: {{base_url}}